# Default values for testapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: shdfx/testimage
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: "testapp"
fullnameOverride: "testapp"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  externalport: 8081
  internalPort: 8081


ingress:
  enabled: "true"
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: test.com
      paths:
        - path: /
          pathType: ImplementationSpecific
      backend:
          serviceName: internal
          servicePort: 8081 
  tls: 
    - hosts:
      - test.com

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
